# Generated by Django 3.2.5 on 2021-07-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ref', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Reference')),
                ('customer_ref', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Reference')),
                ('subscription_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subscription URL')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
            ],
        ),
    ]
