# Generated by Django 3.2.5 on 2021-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('trial', models.CharField(blank=True, max_length=10, null=True)),
                ('subscription_interval', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='create_subscription',
            name='customer_ref',
        ),
        migrations.RemoveField(
            model_name='create_subscription',
            name='subscription_url',
        ),
        migrations.AddField(
            model_name='create_subscription',
            name='interval',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subscription interval'),
        ),
        migrations.AddField(
            model_name='create_subscription',
            name='trial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Trial'),
        ),
    ]
