# Generated by Django 3.2.5 on 2021-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_subscription', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_subscription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
